# Generated by Django 5.2.17 on 2026-08-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("theory_room", "Theory Room"),
                            ("workshop", "Workshop"),
                            ("tool_set", "Tool Set"),
                        ],
                        max_length=32,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("available_quantity", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[
                            ("dual_degree", "Dual Degree"),
                            ("college", "College"),
                        ],
                        max_length=32,
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("blocks", models.JSONField(blank=True, default=list)),
                ("quota_standard_hours", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("theory_hours", models.PositiveIntegerField(default=0)),
                ("practice_hours", models.PositiveIntegerField(default=0)),
                (
                    "student_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules",
                        to="scheduler.studentgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.CreateModel(
            name="TeacherModule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_modules",
                        to="scheduler.module",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_modules",
                        to="scheduler.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "teacher", "module"],
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="modules",
            field=models.ManyToManyField(
                blank=True,
                related_name="teachers",
                through="scheduler.TeacherModule",
                to="scheduler.module",
            ),
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("config_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [models.Index(fields=["code"], name="idx_tenant_code")],
            },
        ),
        migrations.AddField(
            model_name="teachermodule",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_modules",
                to="scheduler.tenant",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="scheduler.tenant",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_groups",
                to="scheduler.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_type",
                    models.CharField(
                        choices=[("theory", "Theory"), ("practice", "Practice")],
                        max_length=16,
                    ),
                ),
                ("duration_slots", models.PositiveIntegerField(default=1)),
                (
                    "tier",
                    models.CharField(
                        choices=[("culture", "Culture"), ("vocational", "Vocational")],
                        max_length=16,
                    ),
                ),
                ("assigned_timeslot", models.JSONField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "assigned_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="scheduler.resource",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scheduler.module",
                    ),
                ),
                (
                    "student_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scheduler.studentgroup",
                    ),
                ),
                (
                    "assigned_teachers",
                    models.ManyToManyField(
                        blank=True, related_name="sessions", to="scheduler.teacher"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scheduler.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "module", "student_group"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("solving", "Solving"),
                            ("solved", "Solved"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[("culture", "Culture"), ("vocational", "Vocational")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("week_start", models.DateField(blank=True, null=True)),
                ("objective_value", models.FloatField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scheduler.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "-id"],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="scheduler.tenant",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="scheduler.tenant",
            ),
        ),
        migrations.CreateModel(
            name="ConstraintRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("unavailability", "Unavailability"),
                            ("resource_requirement", "Resource Requirement"),
                            ("capacity_limit", "Capacity Limit"),
                            ("quota_limit", "Quota Limit"),
                            ("preference", "Preference"),
                            ("exclusion", "Exclusion"),
                            ("adjacency", "Adjacency"),
                            ("distribution", "Distribution"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("scope_json", models.JSONField(blank=True, default=dict)),
                ("params_json", models.JSONField(blank=True, default=dict)),
                (
                    "hardness",
                    models.CharField(
                        choices=[("hard", "Hard"), ("soft", "Soft")],
                        default="hard",
                        max_length=8,
                    ),
                ),
                ("weight", models.IntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraint_rules",
                        to="scheduler.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "type", "hardness"],
            },
        ),
        migrations.AddIndex(
            model_name="teachermodule",
            index=models.Index(fields=["tenant", "teacher"], name="idx_tm_t_teacher"),
        ),
        migrations.AddIndex(
            model_name="teachermodule",
            index=models.Index(fields=["tenant", "module"], name="idx_tm_t_module"),
        ),
        migrations.AddConstraint(
            model_name="teachermodule",
            constraint=models.UniqueConstraint(
                fields=("teacher", "module"), name="uq_tm_teacher_module"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["tenant", "code"], name="idx_teacher_t_code"),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_teacher_tenant_code"
            ),
        ),
        migrations.AddIndex(
            model_name="studentgroup",
            index=models.Index(
                fields=["tenant", "code"], name="idx_studentgroup_t_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentgroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_studentgroup_t_code"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["tenant", "tier"], name="idx_session_t_tier"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["tenant", "is_locked"], name="idx_session_t_locked"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["tenant", "status"], name="idx_schedule_t_status"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["tenant", "tier"], name="idx_schedule_t_tier"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["tenant", "code"], name="idx_resource_t_code"),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_resource_t_code"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(fields=["tenant", "code"], name="idx_module_t_code"),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_module_t_code"
            ),
        ),
        migrations.AddIndex(
            model_name="constraintrule",
            index=models.Index(fields=["tenant", "active"], name="idx_crule_t_active"),
        ),
        migrations.AddIndex(
            model_name="constraintrule",
            index=models.Index(fields=["tenant", "type"], name="idx_crule_t_type"),
        ),
    ]
