# Generated by Django 5.2.17 on 2026-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="weights_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
