# Generated by Django 5.2.17 on 2026-08-13 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_schedule_weights_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("solving", "Solving"),
                    ("solved", "Solved"),
                    ("failed", "Failed"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SolveJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("solving", "Solving"),
                            ("solved", "Solved"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("building_model", "Building Model"),
                            ("solving", "Solving"),
                            ("post_processing", "Post Processing"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("objective_value", models.FloatField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("metrics_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solve_jobs",
                        to="scheduler.schedule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solve_jobs",
                        to="scheduler.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="idx_solvejob_t_status"
                    )
                ],
            },
        ),
    ]
