# Generated by Django 5.0.6 on 2026-08-21 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0004_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="constraintrule",
            name="priority",
            field=models.CharField(
                choices=[("high", "Cao"), ("medium", "Trung bình"), ("low", "Thấp")],
                default="low",
                help_text="Cao = cố giữ bằng mọi giá; Thấp = bỏ được khi bí",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="inherited_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Phiên bản gốc mà lịch này kế thừa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived",
                to="scheduler.schedule",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_manual_edit",
            field=models.BooleanField(
                default=False, help_text="Đã tinh chỉnh tay sau khi bộ giải chạy"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_schedules",
                to="scheduler.user",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="unplaced_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Số buổi chưa xếp được"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="week_number",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Tuần thứ mấy trong năm học (01–46)", null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Ghim trước khi chạy bộ giải (Chào cờ, Sinh hoạt…)",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="location",
            field=models.CharField(
                choices=[
                    ("on_campus", "Tại trường"),
                    ("enterprise", "Doanh nghiệp"),
                    ("online", "Trực tuyến"),
                ],
                default="on_campus",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Phương án TKB chứa buổi học này",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="scheduler.schedule",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="hazardous",
            field=models.BooleanField(
                default=False,
                help_text="Nghề nặng nhọc, độc hại — trần thực hành 10 thay vì 18",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="occupation",
            field=models.CharField(
                blank=True, default="", help_text="Tên nghề", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="days_off_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="teacher",
            name="max_periods_per_session",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="min_periods_per_session",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="moet_code",
            field=models.CharField(
                blank=True, default="", help_text="Mã định danh Bộ GD&ĐT", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Quản trị hệ thống"),
                    ("registrar", "Phòng Đào tạo"),
                    ("dean", "Trưởng khoa"),
                    ("teacher", "Giáo viên"),
                    ("student", "Sinh viên"),
                ],
                db_index=True,
                default="registrar",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Liên kết tài khoản với hồ sơ giáo viên",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="scheduler.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="constraintrule",
            name="type",
            field=models.CharField(
                choices=[
                    ("unavailability", "Unavailability"),
                    ("resource_requirement", "Resource Requirement"),
                    ("capacity_limit", "Capacity Limit"),
                    ("quota_limit", "Quota Limit"),
                    ("preference", "Preference"),
                    ("exclusion", "Exclusion"),
                    ("adjacency", "Adjacency"),
                    ("distribution", "Distribution"),
                    ("teacher_no_overlap", "Teacher No Overlap"),
                    ("student_no_overlap", "Student No Overlap"),
                    ("shared_resource_pool", "Shared Resource Pool"),
                    ("group_same_class", "Nhóm cùng lớp văn hoá"),
                    ("shift_by_grade", "Ca học theo khối"),
                    ("capacity_by_type", "Trần sĩ số theo loại buổi"),
                    ("offsite_no_room", "Buổi ngoài trường không chiếm phòng"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("theory", "Theory"),
                    ("practice", "Practice"),
                    ("internship", "Internship"),
                    ("supplementary", "Supplementary"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="enrollment_type",
            field=models.CharField(
                choices=[
                    ("dual_degree", "Dual Degree"),
                    ("college", "College"),
                    ("intermediate", "Intermediate"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="quota_standard_hours",
            field=models.FloatField(
                blank=True,
                help_text="Định mức giờ chuẩn/năm, đặt riêng từng người",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                (
                    "travel_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Thời gian di chuyển tối thiểu tới cơ sở khác, tính bằng phút",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campuses",
                        to="scheduler.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="scheduler.campus",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tổ bộ môn trực thuộc khoa nào",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="scheduler.department",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="scheduler.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="scheduler.department",
            ),
        ),
        migrations.CreateModel(
            name="HomeroomClass",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Khối 10, 11 hoặc 12", null=True
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "culture_shift",
                    models.CharField(
                        choices=[
                            ("morning", "Sáng"),
                            ("afternoon", "Chiều"),
                            ("full_day", "Cả ngày"),
                        ],
                        default="morning",
                        help_text="Ca học văn hoá; ca học nghề là phần bù",
                        max_length=16,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Phòng cố định của lớp văn hoá",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homeroom_classes",
                        to="scheduler.resource",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeroom_classes",
                        to="scheduler.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="homerooms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Các lớp văn hoá góp học sinh vào nhóm nghề này",
                related_name="groups",
                to="scheduler.homeroomclass",
            ),
        ),
        migrations.AddConstraint(
            model_name="campus",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_campus_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_department_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="homeroomclass",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_homeroom_tenant_code"
            ),
        ),
    ]
