# Generated by Django 5.0.6 on 2026-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0005_constraintrule_priority_schedule_inherited_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constraintrule",
            name="type",
            field=models.CharField(
                choices=[
                    ("unavailability", "Unavailability"),
                    ("resource_requirement", "Resource Requirement"),
                    ("capacity_limit", "Capacity Limit"),
                    ("quota_limit", "Quota Limit"),
                    ("preference", "Preference"),
                    ("exclusion", "Exclusion"),
                    ("adjacency", "Adjacency"),
                    ("distribution", "Distribution"),
                    ("teacher_no_overlap", "Teacher No Overlap"),
                    ("student_no_overlap", "Student No Overlap"),
                    ("shared_resource_pool", "Shared Resource Pool"),
                    ("group_same_class", "Nhóm cùng lớp văn hoá"),
                    ("shift_by_grade", "Ca học theo khối"),
                    ("capacity_by_type", "Trần sĩ số theo loại buổi"),
                    ("offsite_no_room", "Buổi ngoài trường không chiếm phòng"),
                    ("teacher_limits", "Ràng buộc cá nhân giáo viên"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
