# Generated by Django 5.0.6 on 2026-08-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0006_alter_constraintrule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="solvejob",
            name="stop_requested",
            field=models.BooleanField(
                default=False,
                help_text="Người dùng đã bấm Dừng; bộ giải dừng ở nghiệm kế tiếp",
            ),
        ),
        migrations.AlterField(
            model_name="solvejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("solving", "Solving"),
                    ("solved", "Solved"),
                    ("failed", "Failed"),
                    ("stopped", "Đã dừng"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
            ),
        ),
    ]
